services:
  main:
    build: ./MainService
    ports:
      - 3000:3000

  logger:
    build: ./Logger

  db:
    image: postgres
    restart: always
    environment:
       - POSTGRES_PASSWORD=root
       - POSTGRES_DB=docker-migrations
       - POSTGRES_USER=postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis

volumes:
  data:
    driver: local
  redis:
    driver: local
